import { writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  featuresFromOpenApiDocument,
  type OpenApiDocument,
} from '../src/features.ts';

const OPENAPI_URL =
  process.env.INDICIA_OPENAPI_URL ?? 'https://api.indicia.app/openapi';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const outFile = path.join(root, 'src/fallback-features.generated.ts');

const res = await fetch(OPENAPI_URL, {
  headers: {
    accept: 'application/json',
    'user-agent': 'indicia-cli-sync-fallback',
  },
});
if (!res.ok) {
  throw new Error(`OpenAPI fetch failed: ${res.status} ${res.statusText}`);
}

const doc = (await res.json()) as OpenApiDocument;
const features = featuresFromOpenApiDocument(doc);
if (!features.length) {
  throw new Error('OpenAPI produced no CLI features');
}

const source = `import type { Feature } from './features.js';

/** Generated by \`pnpm sync-fallback\` from the Indicia OpenAPI spec. Do not edit. */
export const fallbackFeatures: Feature[] = ${JSON.stringify(features, null, 2)};
`;

writeFileSync(outFile, source);
console.log(
  `wrote ${features.length} features to ${path.relative(root, outFile)}`,
);
